apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-google-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intro
  template:
    metadata:
      labels:
        app: intro
    spec:
      containers:
      - name: intro-app
        image: europe-west2-docker.pkg.dev/sample-cluster-403202/intro-repo/go-k8s-google-cluster:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
